# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 15
      uses: actions/setup-java@master
      with:
        java-version: 15
    - name: Build with Maven - run unit tests
      run: mvn -B clean install

  run-integration-tests:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Build with Maven - run integration tests
      run: mvn -B clean install -PintegrationTest

  run-postman-tests:
    needs: run-integration-tests
    runs-on: ubuntu-latest
    steps:
    - name: Build and run Docker image
      run: |
        # docker build -t calculatorservice .
        # nohup docker run -p 8080:8080 calculatorservice &
        docker-compose -f docker-compose.yml up -d
    - name: Wait for Service To Start
      uses: nev7n/wait_for_response@v1
      with:
        url: 'http://localhost:8080/health'
        responseCode: 200
        timeout: 30000
        interval: 500    
    - name: Run Newman tests
      uses: matt-ball/newman-action@master
      with:
        collection: postman/CalculatorService.postman_collection.json
        environment: postman/CalculatorServiceDev.postman_environment.json
